config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  resources :users, :only => [:show]

  unauthenticated :user do
    root :to => 'scales#create'
  end

  authenticated :user do
    root :to => 'users#current_user_home', :as => 'authenticated_root'
  end

  resources :scales do
    resources :notes
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessor :transposition
  belongs_to :scale
  has_closure_tree order: 'frequency'

  validates :frequency, :presence => true

  after_create :increment_note_count
  after_destroy :decrement_note_count

  def transpose(params)
    if params[:transposition] == 'up_octave'
      self.transpose_up_octave
    elsif params[:transposition] == 'down_octave'
      self.transpose_down_octave
    end
  end

  def transpose_up_octave
    self.frequency = self.frequency * 2
    self.save!
  end

  def transpose_down_octave
    self.frequency = self.frequency / 2
    self.save!
  end

  def relative_name
    # MC_REVISIT: don't hard code this
    if self.parent
      if self.name == '8/5 major third down' && self.frequency > self.parent.frequency
        '8/5 minor sixth up'
      elsif self.name == '4/3 perfect fifth down' && self.frequency > self.parent.frequency
        '4/3 perfect fourth up'
      elsif self.name == '3/2 perfect fifth' && self.frequency < self.parent.frequency
        '3/2 perfect fourth down'
      else
        self.name
      end
    else
      self.name
    end
  end

  private

  def increment_note_count
    self.scale.notes_count += 1
    self.scale.save!
  end

  def decrement_note_count
    self.scale.notes_count -= 1
    self.scale.save!
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @scale = Scale.find(params[:scale_id])
    @note = @scale.notes.new
  end

  def create
    @scale = Scale.find(params[:scale_id])
    if params[:frequencies] == ""
      flash[:alert] = "You must enter at least one frequency"
      return redirect_to new_scale_note_path(@scale)
    else
      @scale.create_note(params)
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    end
  end

  def edit
    @note = Note.find(params[:id])
    @scale = Scale.find(params[:scale_id])
  end

  def update
    @scale = Scale.find(params[:scale_id])
    @note = @scale.notes.find(params[:id])
    if params[:transposition]
      @note.transpose(params)
      flash[:notice] = "Note successfully updated!"
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    elsif @note.update(note_params)
      flash[:notice] = "Note successfully updated!"
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    else
      flash[:alert] = "Note did not update! Please try again"
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @scale = @note.scale
    @note.destroy
    flash[:notice] = "Note successfully deleted!"
    respond_to do |format|
      format.html {redirect_to scale_path(@scale)}
      format.js
    end
  end

  def show
  end

  private
  def note_params
    params.require(:note).permit(:frequency, :transposition)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def notes_tree_for(notes)
    notes.map do |note, nested_notes|
      render(note) +
          (nested_notes.size > 0 ? content_tag(:div, notes_tree_for(nested_notes), class: "children") : nil)
    end.join.html_safe
  end
end

app/views/notes/_add_note_dropdown.html.erb
<a class="btn btn-primary btn-outline btn-sm" role="button" data-toggle="collapse" href="#<%= note.id%>addNoteCollapse" aria-expanded="false" aria-controls="<%= note.id %>addNoteCollapse">
  Add Note
</a>
<div class="collapse" id="<%= note.id %>addNoteCollapse">
  <div class="well">

    <%= render partial: "notes/intervals/seconds_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/thirds_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/fourths_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/fifths_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/sixths_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/sevenths_form", locals: { scale: @scale, note: note } %>
    <br>
    <%= render partial: "notes/intervals/octave_form", locals: { scale: @scale, note: note } %>

  </div>
</div>

app/views/notes/_form.html.erb
<%= render('layouts/errors', :object => @note) %>

<%= form_for [@scale, @note], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :frequency %>
    <%= f.text_field :frequency, class: 'form-control' %>
  </div>
  <p><%= f.submit class: "btn btn-success btn-sm btn-outline" %> <%= link_to "Nevermind", scale_path(@scale),  class: "btn btn-warning btn-sm btn-outline" %></p>
<% end %>

app/views/notes/_new.html.erb
<% if current_user == @scale.user %>

  <p>Please enter numbers between 20 and 20000, separated by a comma</p>

  <%= form_tag [@scale, @note], remote: true do %>
    <div class="form-group">
      <%= label_tag :frequencies %>
      <%= text_field_tag :frequencies, "", class:'form-control'%>
    </div>
    <p><%= submit_tag "Add Notes", class: "btn btn-outline btn-success btn-lg bigButton"%></p>
  <% end %>
<% else %>
  <h3>You do not have authorization to add notes to this scale</h3>
<% end %>

app/views/notes/_new_note.html.erb
<% if is_editable? %>

  <p>Please enter numbers between 20 and 20000, separated by a comma</p>

  <%= form_tag [@scale, @note], remote: true do %>
    <div class="form-group">
      <%= label_tag :frequencies %>
      <%= text_field_tag :frequencies, "", class:'form-control'%>
    </div>
    <p><%= submit_tag "Add Notes", class: "btn btn-outline btn-success btn-lg bigButton"%></p>
  <% end %>
<% else %>
  <h3>You do not have authorization to add notes to this scale</h3>
<% end %>

app/views/notes/_note.html.erb
<li class = 'list-group-item'>
  <% if is_editable? %>
    <%= link_to "", scale_note_path(@scale, note), class: 'stopper glyphicon glyphicon-remove btn btn-xs btn-outline btn-danger', :data => {:method => "delete"}, remote: true %>
  <% end %>

  <span id="note_freq-<%=note.id%>"><%= note.relative_name %>
    <% if is_editable? %>
      (<%= link_to note.frequency.round(2).to_s + " hz", edit_scale_note_path(@scale, note), class: 'stopper', remote: true %>)
    <% else %>
      (<%= note.frequency.round(2)%>)
    <% end %>

  </span>

  <% if is_editable? %>
    <%= render partial: "notes/add_note_dropdown", locals: { scale: @scale, note: note } %>
    <%= render partial: 'notes/transpose', locals: { scale: @scale, note: note } %>
  <% end %>

  <button class="note<%=note.id%> btn btn-success glyphicon glyphicon-play"></button>
</li>

app/views/notes/_notes_tree.html.erb
<div class="well">
  <ul class='list-group'>
    <%= content_tag :div, class: "freq_information", data: {notes: @scale.notes } do %>
    <% end %>
    <%= notes_tree_for @scale.notes.hash_tree %>
  </ul>
</div>

app/views/notes/_transpose.html.erb
<a class="btn btn-primary btn-outline btn-sm" role="button" data-toggle="collapse" href="#<%= note.id%>transposeCollapse" aria-expanded="false" aria-controls="<%= note.id %>transposeCollapse">
  Transpose
</a>
<div class="collapse" id="<%= note.id %>transposeCollapse">
  <div class='well'>
    <%= form_tag scale_note_path(@scale, note), class: 'form-inline', method: 'patch', remote: true do %>
      <div class='form-group'>
        <%= hidden_field_tag 'transposition', 'up_octave' %>
      </div>
      <%= submit_tag "octave up", class: "btn btn-outline btn-primary btn-sm stopper"%>
    <% end %>
    <br>

    <%= form_tag scale_note_path(@scale, note), class: 'stopper form-inline', method: 'patch', remote: true do %>
      <div class='form-group'>
        <%= hidden_field_tag 'transposition', 'down_octave' %>
      </div>
      <%= submit_tag "octave down", class: "btn btn-outline btn-primary btn-sm"%>
    <% end %>
  </div>
</div>

app/views/notes/create.js.erb
// $('#add_notes_form').html("");
// $('#add_notes_link').show();
$('#notes_list').html("<%= j render :partial => 'notes/notes_tree', :notes => @scale.notes.hash_tree %>");

$(document).ready(function() {
  var context = new AudioContext;
  if ($('.freq_information').length > 0 ) {

    var notes = $('.freq_information').data('notes').sort(function(a, b) {
      return parseFloat(a.frequency) - parseFloat(b.frequency);
    });
    var notesArray = [];
    var voices = [];

    if (notes !== undefined) {
      notes.forEach(function(note) {
        notesArray.push(note.frequency);
      });
    }
    for (let i = 0; i < notes.length; i++) {
      var voice = {};
      voice.vco = context.createOscillator();
      voice.vco.frequency.value = notes[i].frequency;
      voice.vca = context.createGain();
      voice.vca.gain.value = 0;
      voice.panNode = context.createStereoPanner();
      voice.panNode.pan.value = (Math.random() * (0 - 2) + 2) - 1
      voice.vco.connect(voice.vca);
      voice.vca.connect(voice.panNode);
      voice.panNode.connect(context.destination);
      voice.vco.start(0);
      voices.push(voice);
      $('.note' + notes[i].id).click(function() {
        var $this = $(this);
        $this.toggleClass('note' + notes[i].id);
        if($this.hasClass('note' + notes[i].id)) {
          $this.toggleClass("btn-danger").toggleClass("btn-success");
          $this.toggleClass("glyphicon-stop").toggleClass("glyphicon-play");
          voices[i].vca.gain.value = 0;
        }
        else {
          $this.toggleClass("btn-success").toggleClass("btn-danger");
          $this.toggleClass("glyphicon-play").toggleClass("glyphicon-stop");
          voices[i].vca.gain.value = .25;
        }
      });
      $('.stopper').click(function() {
        for (var i = 0; i < voices.length; i++) {
          voices[i].vca.gain.value = 0;
        }
      });
    }
    $('.stopper').click(function() {
      context.close();
    });
  }
});

app/views/notes/destroy.js.erb
$('#notes_list').html("<%= j render :partial => 'notes/notes_tree', :notes => @scale.notes.hash_tree %>");

$(document).ready(function() {
  var context = new AudioContext;
  if ($('.freq_information').length > 0 ) {

    var notes = $('.freq_information').data('notes').sort(function(a, b) {
      return parseFloat(a.frequency) - parseFloat(b.frequency);
    });
    var notesArray = [];
    var voices = [];

    if (notes !== undefined) {
      notes.forEach(function(note) {
        notesArray.push(note.frequency);
      });
    }
    for (let i = 0; i < notes.length; i++) {
      var voice = {};
      voice.vco = context.createOscillator();
      voice.vco.frequency.value = notes[i].frequency;
      voice.vca = context.createGain();
      voice.vca.gain.value = 0;
      voice.panNode = context.createStereoPanner();
      voice.panNode.pan.value = (Math.random() * (0 - 2) + 2) - 1
      voice.vco.connect(voice.vca);
      voice.vca.connect(voice.panNode);
      voice.panNode.connect(context.destination);
      voice.vco.start(0);
      voices.push(voice);
      $('.note' + notes[i].id).click(function() {
        var $this = $(this);
        $this.toggleClass('note' + notes[i].id);
        if($this.hasClass('note' + notes[i].id)) {
          $this.toggleClass("btn-danger").toggleClass("btn-success");
          $this.toggleClass("glyphicon-stop").toggleClass("glyphicon-play");
          voices[i].vca.gain.value = 0;
        }
        else {
          $this.toggleClass("btn-success").toggleClass("btn-danger");
          $this.toggleClass("glyphicon-play").toggleClass("glyphicon-stop");
          voices[i].vca.gain.value = .25;
        }
      });
      $('.stopper').click(function() {
        for (var i = 0; i < voices.length; i++) {
          voices[i].vca.gain.value = 0;
        }
      });
    }
    $('.stopper').click(function() {
      context.close();
    });
  }
});

app/views/notes/edit.html.erb
<h1>Edit note:</h1>

<%= render 'form' %>

app/views/notes/edit.js.erb
$("#note_freq-<%= @note.id %>").html('<%= j render "form", :object => @note %>');

app/views/notes/new.html.erb
<% if current_user == @scale.user %>

  <p>Please enter numbers between 20 and 20000, separated by a comma</p>

  <%= form_tag [@scale, @note], remote: true do %>
    <div class="form-group">
      <%= label_tag :frequencies %>
      <%= text_field_tag :frequencies, "", class:'form-control'%>
    </div>
    <p><%= submit_tag "Add Notes", class: "btn btn-outline btn-success btn-lg bigButton"%></p>
  <% end %>
<% else %>
  <h3>You do not have authorization to add notes to this scale</h3>
<% end %>

app/views/notes/new.js.erb
$('#add_notes_link').hide();
$('#add_notes_form').html("<%= j render 'new_note' %>");

app/views/notes/update.js.erb
$('#notes_list').html("<%= j render :partial => 'notes/notes_tree', :notes => @scale.notes.hash_tree %>");

$(document).ready(function() {
  var context = new AudioContext;
  if ($('.freq_information').length > 0 ) {

    var notes = $('.freq_information').data('notes').sort(function(a, b) {
      return parseFloat(a.frequency) - parseFloat(b.frequency);
    });
    var notesArray = [];
    var voices = [];

    if (notes !== undefined) {
      notes.forEach(function(note) {
        notesArray.push(note.frequency);
      });
    }
    for (let i = 0; i < notes.length; i++) {
      var voice = {};
      voice.vco = context.createOscillator();
      voice.vco.frequency.value = notes[i].frequency;
      voice.vca = context.createGain();
      voice.vca.gain.value = 0;
      voice.panNode = context.createStereoPanner();
      voice.panNode.pan.value = (Math.random() * (0 - 2) + 2) - 1
      voice.vco.connect(voice.vca);
      voice.vca.connect(voice.panNode);
      voice.panNode.connect(context.destination);
      voice.vco.start(0);
      voices.push(voice);
      $('.note' + notes[i].id).click(function() {
        var $this = $(this);
        $this.toggleClass('note' + notes[i].id);
        if($this.hasClass('note' + notes[i].id)) {
          $this.toggleClass("btn-danger").toggleClass("btn-success");
          $this.toggleClass("glyphicon-stop").toggleClass("glyphicon-play");
          voices[i].vca.gain.value = 0;
        }
        else {
          $this.toggleClass("btn-success").toggleClass("btn-danger");
          $this.toggleClass("glyphicon-play").toggleClass("glyphicon-stop");
          voices[i].vca.gain.value = .25;
        }
      });
      $('.stopper').click(function() {
        for (var i = 0; i < voices.length; i++) {
          voices[i].vca.gain.value = 0;
        }
      });
    }
    $('.stopper').click(function() {
      context.close();
    });
  }
});