config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  resources :users, :only => [:show]

  unauthenticated :user do
    root :to => 'scales#create'
  end

  authenticated :user do
    root :to => 'users#current_user_home', :as => 'authenticated_root'
  end

  resources :scales do
    resources :notes
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/scale.rb
class Scale < ActiveRecord::Base
  has_many :notes
  belongs_to :user, optional: true
  scope :active, -> { where("user_id IS NOT NULL") }
  after_create :set_note_count
  after_create :create_starter_note

  def create_second(params, note)
    if params['second_type'] == 'Minor 5-limit half-step (25/24)'
      return self.notes.create(frequency: note.frequency * 1.04166667, name: '25/24 (Minor 5-limit half-step)')
    elsif params['second_type'] == 'Major five-limit half-step (16/15)'
      return self.notes.create(frequency: note.frequency * 1.06666667, name: '16/15 (Major five-limit half-step)')
    elsif params['second_type'] == 'Minor whole tone (10/9)'
      return self.notes.create(frequency: note.frequency * 1.11111111, name: '10/9 (Minor whole tone)')
    elsif params['second_type'] == 'Major whole tone (9/8)'
      return self.notes.create(frequency: note.frequency * 1.125, name: '9/8 (Major whole tone)')
    end
  end

  def create_third(params, note)
    if params['third_type'] == 'Septimal minor (7/6)'
      return self.notes.create(frequency: note.frequency * 1.166666667, name: '7/6 minor third')
    elsif params['third_type'] == '5-limit major (5/4)'
      return self.notes.create(frequency: note.frequency * 1.25, name: '5/4 major third')
    elsif params['third_type'] == '5-limit minor (6/5)'
      return self.notes.create(frequency: note.frequency * 1.2, name: '6/5 5-limit minor third')
    elsif params['third_type'] == 'Undecimal "median" third (11/9)'
      return self.notes.create(frequency: note.frequency * 1.22222222, name: '11/9 undecimal "median" third')
    elsif params['third_type'] == 'Septimal major (9/7)'
      return self.notes.create(frequency: note.frequency * 1.28571428, name: '9/7 septimal major third')
    end
  end

  def create_fifth(params, note)
    if params['fifth_type'] == 'Perfect (3/2)'
      return self.notes.create(frequency: note.frequency * 1.5, name: '3/2 perfect fifth')
    elsif params['fifth_type'] == 'Augmented (25/16)'
      return self.notes.create(frequency: note.frequency * 1.5625, name: '25/16 augmented fifth')
    elsif params['fifth_type'] == 'Diminished (36/25)'
      return self.notes.create(frequency: note.frequency * 1.44, name: '36/25 diminished fifth')
    end
  end

  def create_seventh(params, note)
    if params['seventh_type'] == '5-limit major (15/8)'
      return self.notes.create(frequency: note.frequency * 1.875, name: '15/8 major seventh')
    elsif params['seventh_type'] == '5-limit large minor (9/5)'
      return self.notes.create(frequency: note.frequency * 1.8, name: '9/5 minor seventh')
    elsif params['seventh_type'] == 'Pythagorean small minor (16/9)'
      return self.notes.create(frequency: note.frequency * 1.777777778, name: '16/9 minor seventh')
    elsif params['seventh_type'] == 'Septimal minor (7/4)'
      return self.notes.create(frequency: note.frequency * 1.75, name: '7/4 septimal minor seventh')
    end
  end

  def create_octave(params, note)
    return self.notes.create(frequency: note.frequency * 2, name: '2/1')
  end

  def create_third_harmonic(params, note)
    return self.notes.create(frequency: note.frequency * 1.5, name: '3/2 third harmonic')
  end

  def create_fifth_harmonic(params, note)
    return self.notes.create(frequency: note.frequency * 1.25, name: '5/4 fifth harmonic')
  end

  def create_seventh_harmonic(params, note)
    return self.notes.create(frequency: note.frequency * 1.75, name: '7/4 seventh harmonic')
  end

  def create_eleventh_harmonic(params, note)
    return self.notes.create(frequency: note.frequency * 1.375, name: '11/8 eleventh harmonic')
  end

  def create_thirteenth_harmonic(params, note)
    return self.notes.create(frequency: note.frequency * 1.625, name: '13/8 eleventh harmonic')
  end

  def create_fourth(params, note)
    if params['fourth_type'] == 'Perfect (4/3)'
      return self.notes.create(frequency: note.frequency * 1.333333333, name: '4/3 perfect fourth')
    elsif params['fourth_type'] == 'Harmonic Tritone (11/8)'
      return self.notes.create(frequency: note.frequency * 1.375, name: '11/8 harmonic tritone')
    elsif params['fourth_type'] == 'Five-Limit Tritone (45/32)'
      return self.notes.create(frequency: note.frequency * 1.40625, name: '45/32 five-limit tritone')
    elsif params['fourth_type'] == 'Septimal fourth (21/16)'
      return self.notes.create(frequency: note.frequency * 1.3125, name: '21/16 septimal fourth')
    end
  end

  def create_sixth(params, note)
    if params['sixth_type'] == 'Five-limit minor (8/5)'
      return self.notes.create(frequency: note.frequency * 1.6, name: '8/5 five-limit minor')
    elsif params['sixth_type'] == '5-limit major (5/3)'
      return self.notes.create(frequency: note.frequency * 1.666666667, name: '5/3 5-limit major')
    elsif params['sixth_type'] == 'Undecimal minor (11/7)'
      return self.notes.create(frequency: note.frequency * 1.571428, name: '11/7 undecimal minor sixth')
    elsif params['sixth_type'] == 'Overtone sixth (13/8)'
      return self.notes.create(frequency: note.frequency * 1.625, name: '13/8 overtone sixth')
    elsif params['sixth_type'] == 'Septimal major (12/7)'
      return self.notes.create(frequency: note.frequency * 1.7142857, name: '12/7 septimal major sixth')
    end
  end

  def parse_frequencies(params)
    notes_array = params[:frequencies].split(',')
    notes_array.each do |note|
      note.strip
      self.notes.create(frequency: note)
    end
  end

  def create_note(params)
    if params['note_id']
      note = self.notes.find(params['note_id'])
    end
    if params['third_type']
      child = self.create_third(params, note)
      note.add_child child
    elsif params['fifth_type']
      child = self.create_fifth(params, note)
      note.add_child child
    elsif params['seventh_type']
      child = self.create_seventh(params, note)
      note.add_child child
    elsif params['fourth_type']
      child = self.create_fourth(params, note)
      note.add_child child
    elsif params['octave']
      child = self.create_octave(params, note)
      note.add_child child
    elsif params['second_type']
      child = self.create_second(params, note)
      note.add_child child
    elsif params['sixth_type']
      child = self.create_sixth(params, note)
      note.add_child child
    else
      self.parse_frequencies(params)
    end
  end

  def create_harmonic(params)
    if params['note_id']
      note = self.notes.find(params['note_id'])
    end
    if params['octave']
      child = self.create_octave(params, note)
      note.add_child child
    elsif params['third_harmonic']
      child = self.create_third_harmonic(params, note)
      note.add_child child
    elsif params['fifth_harmonic']
      child = self.create_fifth_harmonic(params, note)
      note.add_child child
    elsif params['seventh_harmonic']
      child = self.create_seventh_harmonic(params, note)
      note.add_child child
    elsif params['eleventh_harmonic']
      child = self.create_eleventh_harmonic(params, note)
      note.add_child child
    elsif params['thirteenth_harmonic']
      child = self.create_thirteenth_harmonic(params, note)
      note.add_child child
    end
  end

  private

  def create_starter_note
    self.notes.create(frequency: 150, name: '1/1 root')
  end

  def set_note_count
    self.notes_count = 0
    self.save!
  end
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :create]

  def index
    @scales = Scale.active
  end

  def show
    @scale = Scale.find(params[:id])
    @notes = @scale.notes.hash_tree
  end

  def new
    @scale = Scale.new
  end

  def create
    if current_user
      @scale = current_user.scales.new(name: 'New Scale ' + Scale.count.to_s)
      flash[:notice] = "Scale successfully added!"
    else
      @scale = find_or_create_starter_scale
    end
    if @scale.save
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    else
      flash[:alert] = "Scale did not save! Please try again"
      render :new
    end
  end

  def edit
    @scale = Scale.find(params[:id])
  end

  def update
    @scale= Scale.find(params[:id])
    if @scale.update(scale_params)
      flash[:notice] = "Scale successfully updated!"
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    else
      flash[:alert] = "Scale did not update! Please try again"
      render :edit
    end
  end

  def destroy
    @scale = Scale.find(params[:id])
    @scale.destroy
    flash[:notice] = "Scale successfully deleted!"
    redirect_to scales_path
  end

  private
  def scale_params
    params.require(:scale).permit(:name)
  end

  def find_or_create_starter_scale
    @scale = Scale.find_by(user_id: nil, notes_count: 1)
    if @scale == nil
      @scale = Scale.create(name: 'Sandbox Scale ' + Scale.count.to_s)
    end
    return @scale
  end

end

app/helpers/scales_helper.rb
module ScalesHelper
  def is_editable?
    @scale.user == nil || @scale.user == current_user
  end
end

app/views/scales/_form.html.erb
<%= render "layouts/errors", :object => @scale %>

<%= form_for @scale, html: {id: :add_scale_form}, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="bigButton">
    <%= f.submit class: "btn btn-success btn-outline"%>
  </div>
<% end %>

app/views/scales/create.js.erb
$('#newScaleForm').html("");
$('#newScaleButton').show();
$('#scales_list').append('<li class="list-group-item"><%= link_to @scale.name, scale_path(@scale) %></li>');

app/views/scales/edit.html.erb
<h1>Edit Scale:</h1>

<%= render "form" %>

app/views/scales/edit.js.erb
$("#edit_scale").html('<%= j render "form", :object => @scale %>');

app/views/scales/index.html.erb
<h1>Browse User Scales:</h1>

<br>

<% if @scales.any? %>
  <div class="well">
    <ul id="scales_list" class="list-group">
      <% @scales.each do |scale| %>
        <li class="list-group-item">
          <h4 class='list-group-item-heading'><%= link_to scale.name, scale_path(scale) %>
            <% if scale.notes_count > 1 %>
              <span style = 'float: right'class="badge"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>  <%=scale.notes_count%></span>
            <% end %>
          </h4>
          <p class="list-group-item-text">by <%= link_to scale.user.name, user_path(scale.user) %></p>
        </li>
      <% end %>
    </ul>
  </div>

<% else %>
  <h5>There are no scales, click below to add one</h5>

<% end %>

<hr>
<div id= "newScaleButton" class="bigButton centered">
  <%= link_to "New Scale", scales_path, :method => :post, class: 'btn btn-primary btn-outline btn-lg centered' %>
</div>
<br>

app/views/scales/new.html.erb
<h1>Name your Scale:</h1>

<%= render "form" %>

app/views/scales/new.js.erb
$('#newScaleButton').hide();
$('#newScaleForm').html('<%= j render("form") %>');

app/views/scales/show.html.erb
<h1 id="scale_name" align = 'center' class=''><%= @scale.name %></h1>
<% if @scale.user &&  @scale.user == current_user %>
  <div class="outer centered">
    <div id="edit_scale" class="inner">
      <%= link_to "Edit Scale Name", edit_scale_path(@scale), class:"btn btn-warning btn-outline btn-xs", remote: true %>
    </div>
    <div class="inner">
      <%= link_to "Delete Scale", scale_path(@scale), class: "btn btn-danger btn-outline btn-xs",
                               :data => {:confirm => "You sure?",
                                         :method => "delete"} %>
    </div>
  </div>
<% end %>
<div id="notes_list">
  <% if @scale.notes.any? %>

    <%= render :partial => 'notes/notes_tree', :object => @notes %>
  <% else %>
    <p class="bufferText">This scale has no notes yet. <%= link_to 'Add one.', new_scale_note_path(@scale), remote: true %></p>

  <% end %>
</div>

<div id="add_notes_form">
</div>

<% unless current_user || @scale.user %>
  <div class='container centered well'>
    <ul class='list-group'>
      <li class='list-group-item'>
        <h3 align ='center'>Log in to save your scale:</h3>
        <div align = 'center'>
        <%= link_to "Sign up", new_user_registration_path(scale_id: @scale)  %> |
        <%= link_to "Log in", new_user_session_path(scale_id: @scale) %>
        </div>
      </li>
    </ul>
  </div>
  <br>
  <br>
<% else %>
  <div class='container centered'>
    <%= link_to "New Scale", scales_path, :method => :post, class: 'btn btn-primary btn-outline btn-lg centered' %>
  </div>
  <br>
<% end %>

app/views/scales/update.js.erb
$("#edit_scale").html('<%= link_to "Edit Scale Name", edit_scale_path(@scale), class:"btn btn-warning btn-outline btn-xs", remote: true %>');
$("#scale_name").html('<%= @scale.name %>');