config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  resources :users, :only => [:show]

  unauthenticated :user do
    root :to => 'scales#create'
  end

  authenticated :user do
    root :to => 'users#current_user_home', :as => 'authenticated_root'
  end

  resources :scales do
    resources :notes
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class='navbar-toggle' data-toggle='collapse' data-target="#bs-example-navbar-collapse-1">
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to image_tag("nodes.svg", height: 50), root_path, :class=>"" %>


    </div>

    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav'>
        <li><%= link_to 'Browse Scales', scales_path %></li>
        <li><%= link_to "New Scale", scales_path, :method => :post %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=current_user.email%><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'View Profile', user_path(current_user) %></li>
            <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path  %></li>
          <li><%= link_to "Log in", new_user_session_path  %></li>
        <% end %>
      </ul>

  </div>
</nav>