config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  resources :users, :only => [:show]

  unauthenticated :user do
    root :to => 'scales#create'
  end

  authenticated :user do
    root :to => 'users#current_user_home', :as => 'authenticated_root'
  end

  resources :scales do
    resources :notes
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessor :transposition
  belongs_to :scale
  has_closure_tree order: 'frequency'

  validates :frequency, :presence => true

  after_create :increment_note_count
  after_destroy :decrement_note_count

  def transpose(params)
    if params[:transposition] == 'up_octave'
      self.transpose_up_octave
    elsif params[:transposition] == 'down_octave'
      self.transpose_down_octave
    end
  end

  def transpose_up_octave
    self.frequency = self.frequency * 2
    self.save!
  end

  def transpose_down_octave
    self.frequency = self.frequency / 2
    self.save!
  end

  def relative_name
    # MC_REVISIT: don't hard code this
    if self.parent
      if self.name == '8/5 major third down' && self.frequency > self.parent.frequency
        '8/5 minor sixth up'
      elsif self.name == '4/3 perfect fifth down' && self.frequency > self.parent.frequency
        '4/3 perfect fourth up'
      elsif self.name == '3/2 perfect fifth' && self.frequency < self.parent.frequency
        '3/2 perfect fourth down'
      else
        self.name
      end
    else
      self.name
    end
  end

  private

  def increment_note_count
    self.scale.notes_count += 1
    self.scale.save!
  end

  def decrement_note_count
    self.scale.notes_count -= 1
    self.scale.save!
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @scale = Scale.find(params[:scale_id])
    @note = @scale.notes.new
  end

  def create
    @scale = Scale.find(params[:scale_id])
    if params[:frequencies] == ""
      flash[:alert] = "You must enter at least one frequency"
      return redirect_to new_scale_note_path(@scale)
    else
      @scale.create_note(params)
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    end
  end

  def edit
    @note = Note.find(params[:id])
    @scale = Scale.find(params[:scale_id])
  end

  def update
    @scale = Scale.find(params[:scale_id])
    @note = @scale.notes.find(params[:id])
    if params[:transposition]
      @note.transpose(params)
      flash[:notice] = "Note successfully updated!"
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    elsif @note.update(note_params)
      flash[:notice] = "Note successfully updated!"
      respond_to do |format|
        format.html {redirect_to scale_path(@scale)}
        format.js
      end
    else
      flash[:alert] = "Note did not update! Please try again"
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @scale = @note.scale
    @note.destroy
    flash[:notice] = "Note successfully deleted!"
    respond_to do |format|
      format.html {redirect_to scale_path(@scale)}
      format.js
    end
  end

  def show
  end

  private
  def note_params
    params.require(:note).permit(:frequency, :transposition)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def notes_tree_for(notes)
    notes.map do |note, nested_notes|
      render(note) +
          (nested_notes.size > 0 ? content_tag(:div, notes_tree_for(nested_notes), class: "children") : nil)
    end.join.html_safe
  end
end

app/views/notes/intervals/_fifths_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%= label_tag :fourth_type, "Fifth:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :fifth_type, options_for_select([ "Diminished (36/25)", "Perfect (3/2)", "Augmented (25/16)"], "Perfect (3/2)"), class: 'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_fourths_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%= label_tag :fourth_type, "Fourth:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :fourth_type, options_for_select([ "Septimal fourth (21/16)", "Perfect (4/3)", "Harmonic Tritone (11/8)", 'Five-Limit Tritone (45/32)'], "Perfect (4/3)"), class: 'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_octave_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class='form-group'>
    <%= label_tag :octave, "Octave (2/1):" %>
    <%= hidden_field_tag 'octave' %>
    <%= hidden_field_tag 'note_id', note.id %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_seconds_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%= label_tag :second_type, "Second:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :second_type, options_for_select([ "Minor 5-limit half-step (25/24)", "Major 5-limit half-step (16/15)", 'Minor whole tone (10/9)', 'Major whole tone (9/8)' ], 'Major whole tone (9/8)'), class: 'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_sevenths_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%= label_tag :seventh_type, "Seventh:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :seventh_type, options_for_select([ "Septimal minor (7/4)", "Pythagorean small minor (16/9)", "5-limit large minor (9/5)", "5-limit major (15/8)"  ]), class: 'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_sixths_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class="form-group">
    <%= label_tag :sixth_type, "Sixth:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :sixth_type, options_for_select(["Undecimal minor (11/7)", "Five-limit minor (8/5)", "Overtone sixth (13/8)", "5-limit major (5/3)", "Septimal major (12/7)"], "5-limit major (5/3)"), class: 'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper"%>
<% end %>

app/views/notes/intervals/_thirds_form.html.erb
<%= form_tag scale_notes_path(@scale), class: 'form-inline', remote: true do %>
  <div class='form-group'>
    <%= label_tag :third_type, "Third:" %>
    <%= hidden_field_tag 'note_id', note.id %>
    <%= select_tag :third_type, options_for_select([ "Septimal minor (7/6)", "5-limit minor (6/5)", 'Undecimal "median" third (11/9)', "5-limit major (5/4)", "Septimal major (9/7)"], "5-limit major (5/4)"), class:'form-control' %>
  </div>
  <%= submit_tag "Add", class: "btn btn-outline btn-success btn-sm stopper" %>
<% end %>